[build]
builder = "nixpacks"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t pages"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = {}
